"""allow pruning flash webhook payloads

Revision ID: 023b9dcb321c
Revises: 4f4bd1f97c37
Create Date: 2026-08-25 10:33:36.351423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '023b9dcb321c'
down_revision = '4f4bd1f97c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flash_webhook_event', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flash_webhook_event', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
