"""add error column

Revision ID: 0e202fe97de8
Revises: bd0cdc310e79
Create Date: 2026-04-28 10:05:10.632889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e202fe97de8'
down_revision = 'bd0cdc310e79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_request', sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_request', 'error')
    # ### end Alembic commands ###
