"""add graperank preset columns

Revision ID: 1ce55ff8dad6
Revises: 503c7af3e487
Create Date: 2026-04-23 13:05:50.480105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce55ff8dad6'
down_revision = '503c7af3e487'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_nsec', sa.Column('graperank_preset', sa.String(), nullable=True))
    op.add_column('brainstorm_request', sa.Column('graperank_preset_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_request', 'graperank_preset_used')
    op.drop_column('brainstorm_nsec', 'graperank_preset')
    # ### end Alembic commands ###
