"""add count_values column to brainstormRequest

Revision ID: 1d144470cb48
Revises: 819a28e92073
Create Date: 2026-02-16 13:49:02.707278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d144470cb48'
down_revision = '819a28e92073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_request', sa.Column('count_values', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_request', 'count_values')
    # ### end Alembic commands ###
