"""add nostr transferer table

Revision ID: 478cd612b028
Revises: edad65dd387f
Create Date: 2025-12-30 19:33:22.294291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478cd612b028'
down_revision = 'edad65dd387f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brainstorm_nostr_relay_transfer',
    sa.Column('private_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('oldest', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('private_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brainstorm_nostr_relay_transfer')
    # ### end Alembic commands ###
