"""add graperank preset tables

Revision ID: 4fcfe9570a50
Revises: 8b41afd141b1
Create Date: 2026-04-27 12:31:32.043198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fcfe9570a50'
down_revision = '8b41afd141b1'
branch_labels = None
depends_on = None


# Factory defaults seeded on first migration. After this runs, the DB is the
# source of truth — admins edit values via the admin endpoint, not by editing
# this file. To change defaults for new deployments, write a follow-up migration.
_SEED = {
    "DEFAULT": {
        "rigor": 0.5,
        "attenuation_factor": 0.85,
        "follow_rating": 1.0,
        "follow_confidence": 0.03,
        "mute_rating": -0.1,
        "mute_confidence": 0.5,
        "report_rating": -0.1,
        "report_confidence": 0.5,
        "follow_confidence_of_observer": 0.5,
        "verified_followers_influence_cutoff": 0.02,
        "verified_reporters_influence_cutoff": 0.1,
        "verified_muters_influence_cutoff": 0.01,
    },
    "PERMISSIVE": {
        "rigor": 0.3,
        "attenuation_factor": 0.95,
        "follow_rating": 1.0,
        "follow_confidence": 0.1,
        "mute_rating": 0.0,
        "mute_confidence": 0.1,
        "report_rating": 0.0,
        "report_confidence": 0.1,
        "follow_confidence_of_observer": 0.1,
        "verified_followers_influence_cutoff": 0.002,
        "verified_reporters_influence_cutoff": 0.002,
        "verified_muters_influence_cutoff": 0.002,
    },
    "RESTRICTIVE": {
        "rigor": 0.65,
        "attenuation_factor": 0.5,
        "follow_rating": 1.0,
        "follow_confidence": 0.03,
        "mute_rating": -0.9,
        "mute_confidence": 0.9,
        "report_rating": -0.9,
        "report_confidence": 0.9,
        "follow_confidence_of_observer": 0.5,
        "verified_followers_influence_cutoff": 0.5,
        "verified_reporters_influence_cutoff": 0.5,
        "verified_muters_influence_cutoff": 0.5,
    },
}

_FIELDS = list(next(iter(_SEED.values())).keys())


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graperank_preset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rigor', sa.Float(), nullable=False),
    sa.Column('attenuation_factor', sa.Float(), nullable=False),
    sa.Column('follow_rating', sa.Float(), nullable=False),
    sa.Column('follow_confidence', sa.Float(), nullable=False),
    sa.Column('mute_rating', sa.Float(), nullable=False),
    sa.Column('mute_confidence', sa.Float(), nullable=False),
    sa.Column('report_rating', sa.Float(), nullable=False),
    sa.Column('report_confidence', sa.Float(), nullable=False),
    sa.Column('follow_confidence_of_observer', sa.Float(), nullable=False),
    sa.Column('verified_followers_influence_cutoff', sa.Float(), nullable=False),
    sa.Column('verified_reporters_influence_cutoff', sa.Float(), nullable=False),
    sa.Column('verified_muters_influence_cutoff', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graperank_preset_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preset_id', sa.String(), nullable=False),
    sa.Column('rigor', sa.Float(), nullable=False),
    sa.Column('attenuation_factor', sa.Float(), nullable=False),
    sa.Column('follow_rating', sa.Float(), nullable=False),
    sa.Column('follow_confidence', sa.Float(), nullable=False),
    sa.Column('mute_rating', sa.Float(), nullable=False),
    sa.Column('mute_confidence', sa.Float(), nullable=False),
    sa.Column('report_rating', sa.Float(), nullable=False),
    sa.Column('report_confidence', sa.Float(), nullable=False),
    sa.Column('follow_confidence_of_observer', sa.Float(), nullable=False),
    sa.Column('verified_followers_influence_cutoff', sa.Float(), nullable=False),
    sa.Column('verified_reporters_influence_cutoff', sa.Float(), nullable=False),
    sa.Column('verified_muters_influence_cutoff', sa.Float(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_graperank_preset_history_preset_id',
        'graperank_preset_history',
        ['preset_id'],
    )
    # ### end Alembic commands ###

    preset_table = sa.table(
        'graperank_preset',
        sa.column('id', sa.String),
        *[sa.column(f, sa.Float) for f in _FIELDS],
    )
    history_table = sa.table(
        'graperank_preset_history',
        sa.column('preset_id', sa.String),
        *[sa.column(f, sa.Float) for f in _FIELDS],
        sa.column('change_type', sa.String),
        sa.column('changed_by', sa.String),
    )

    op.bulk_insert(
        preset_table,
        [{"id": pid, **vals} for pid, vals in _SEED.items()],
    )
    op.bulk_insert(
        history_table,
        [
            {"preset_id": pid, **vals, "change_type": "CREATE", "changed_by": None}
            for pid, vals in _SEED.items()
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_graperank_preset_history_preset_id',
        table_name='graperank_preset_history',
    )
    op.drop_table('graperank_preset_history')
    op.drop_table('graperank_preset')
    # ### end Alembic commands ###
