"""add encrypted_nsec column

Revision ID: 503c7af3e487
Revises: 781cce9f0822
Create Date: 2026-04-10 10:07:47.579897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503c7af3e487'
down_revision = '781cce9f0822'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_nsec', sa.Column('encrypted_nsec', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_nsec', 'encrypted_nsec')
    # ### end Alembic commands ###
