"""add events column to  nostr transferer table

Revision ID: 5411ca1a52c4
Revises: 478cd612b028
Create Date: 2025-12-30 19:40:43.783055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5411ca1a52c4'
down_revision = '478cd612b028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_nostr_relay_transfer', sa.Column('events', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_nostr_relay_transfer', 'events')
    # ### end Alembic commands ###
