"""add_more_nsec_fields_and_add_more_status_to_brainstorm_instance

Revision ID: 5daaa7743ade
Revises: 75e7de43ccf0
Create Date: 2026-02-05 16:05:05.812868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5daaa7743ade'
down_revision = '75e7de43ccf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_nsec', sa.Column('last_time_triggered_graperank', sa.DateTime(), nullable=True))
    op.add_column('brainstorm_nsec', sa.Column('last_time_calculated_graperank', sa.DateTime(), nullable=True))
    op.add_column('brainstorm_request', sa.Column('status_ta_publication', sa.String(length=128), server_default='waiting', nullable=False))
    op.add_column('brainstorm_request', sa.Column('status_internal_brainstorm_publication', sa.String(length=128), server_default='waiting', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_request', 'status_internal_brainstorm_publication')
    op.drop_column('brainstorm_request', 'status_ta_publication')
    op.drop_column('brainstorm_nsec', 'last_time_calculated_graperank')
    op.drop_column('brainstorm_nsec', 'last_time_triggered_graperank')
    # ### end Alembic commands ###
