"""add billing_plan, user_subscription, scheduling_source

Revision ID: 623266c1f4db
Revises: 1bca8bddda64
Create Date: 2026-08-25 09:43:23.248279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623266c1f4db'
down_revision = '1bca8bddda64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flash_service_id', sa.String(), nullable=False),
    sa.Column('flash_plan_id', sa.String(), nullable=False),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('scheduling_id', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scheduling_id'], ['scheduling.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flash_service_id', 'flash_plan_id', name='uq_billing_plan_flash_ids')
    )
    op.create_table('user_subscription',
    sa.Column('pubkey', sa.String(), nullable=False),
    sa.Column('flash_subscription_id', sa.String(), nullable=False),
    sa.Column('flash_subscriber_id', sa.String(), nullable=True),
    sa.Column('billing_plan_id', sa.Integer(), nullable=False),
    sa.Column('granted_scheduling_id', sa.Integer(), nullable=True),
    sa.Column('flash_status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(), nullable=True),
    sa.Column('cancel_effective_date', sa.DateTime(), nullable=True),
    sa.Column('rail', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_plan_id'], ['billing_plan.id'], ),
    sa.ForeignKeyConstraint(['granted_scheduling_id'], ['scheduling.id'], ),
    sa.PrimaryKeyConstraint('pubkey')
    )
    op.create_index(op.f('ix_user_subscription_email'), 'user_subscription', ['email'], unique=False)
    op.create_index(op.f('ix_user_subscription_flash_subscription_id'), 'user_subscription', ['flash_subscription_id'], unique=False)
    op.add_column('brainstorm_nsec', sa.Column('scheduling_source', sa.String(), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_nsec', 'scheduling_source')
    op.drop_index(op.f('ix_user_subscription_flash_subscription_id'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_email'), table_name='user_subscription')
    op.drop_table('user_subscription')
    op.drop_table('billing_plan')
    # ### end Alembic commands ###
