"""add Brainstorm Request table

Revision ID: 73fba8b6d436
Revises:
Create Date: 2025-12-02 12:40:22.893301

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73fba8b6d436"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brainstorm_request",
        sa.Column("private_id", sa.Integer(), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "ongoing",
                "success",
                "failure",
                name="brainstormrequeststatus",
                native_enum=False,
            ),
            server_default="waiting",
            nullable=False,
        ),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("parameters", sa.String(), nullable=False),
        sa.Column("algorithm", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("private_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("brainstorm_request")
    # ### end Alembic commands ###
