"""add unique kind constraint

Revision ID: 75e7de43ccf0
Revises: 5411ca1a52c4
Create Date: 2025-12-30 20:03:13.841749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e7de43ccf0'
down_revision = '5411ca1a52c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_brainstorm_nostr_relay_transfer_kind', 'brainstorm_nostr_relay_transfer', ['kind'])
    op.create_unique_constraint(None, 'brainstorm_nostr_relay_transfer', ['kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brainstorm_nostr_relay_transfer', type_='unique')
    op.drop_constraint('uq_brainstorm_nostr_relay_transfer_kind', 'brainstorm_nostr_relay_transfer', type_='unique')
    # ### end Alembic commands ###
