"""add new column started_at to brainstorm_nostr_relay_transfer

Revision ID: 781cce9f0822
Revises: 1d144470cb48
Create Date: 2026-02-19 21:14:50.131022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781cce9f0822'
down_revision = '1d144470cb48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_nostr_relay_transfer', sa.Column('started_at', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_nostr_relay_transfer', 'started_at')
    # ### end Alembic commands ###
