"""add pubkey column to brainstormRequest

Revision ID: 819a28e92073
Revises: 5daaa7743ade
Create Date: 2026-02-06 13:41:50.454819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819a28e92073'
down_revision = '5daaa7743ade'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_request', sa.Column('pubkey', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_request', 'pubkey')
    # ### end Alembic commands ###
