"""add list of published TA pubkeys

Revision ID: 8497ccf42093
Revises: 0e202fe97de8
Create Date: 2026-05-04 09:14:41.021733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8497ccf42093'
down_revision = '0e202fe97de8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_nsec', sa.Column('last_published_pubkeys', sa.LargeBinary(), nullable=True))
    op.add_column('brainstorm_nsec', sa.Column('last_published_graperank_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'brainstorm_nsec', 'brainstorm_request', ['last_published_graperank_request_id'], ['private_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brainstorm_nsec', type_='foreignkey')
    op.drop_column('brainstorm_nsec', 'last_published_graperank_request_id')
    op.drop_column('brainstorm_nsec', 'last_published_pubkeys')
    # ### end Alembic commands ###
