"""add graperank params column

Revision ID: 8b41afd141b1
Revises: 1ce55ff8dad6
Create Date: 2026-04-24 12:23:15.552642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b41afd141b1'
down_revision = '1ce55ff8dad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_request', sa.Column('graperank_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_request', 'graperank_params')
    # ### end Alembic commands ###
