"""add is_observer_search_available column

Revision ID: 911619fd5326
Revises: 8497ccf42093
Create Date: 2026-06-02 15:10:11.954303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911619fd5326'
down_revision = '8497ccf42093'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_nsec', sa.Column('is_observer_search_available', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_nsec', 'is_observer_search_available')
    # ### end Alembic commands ###
