"""add user graperank custom param field

Revision ID: bd0cdc310e79
Revises: 4fcfe9570a50
Create Date: 2026-04-27 15:16:12.118888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd0cdc310e79'
down_revision = '4fcfe9570a50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brainstorm_nsec', sa.Column('graperank_custom_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brainstorm_nsec', 'graperank_custom_params')
    # ### end Alembic commands ###
