"""add nostr_nsec table

Revision ID: edad65dd387f
Revises: 73fba8b6d436
Create Date: 2025-12-14 15:29:01.227810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edad65dd387f'
down_revision = '73fba8b6d436'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brainstorm_nsec',
    sa.Column('nsec', sa.String(), nullable=False),
    sa.Column('pubkey', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pubkey')
    )
    op.alter_column('brainstorm_request', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brainstorm_request', 'status',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::character varying"))
    op.drop_table('brainstorm_nsec')
    # ### end Alembic commands ###
